### ISSUE TITLE
2D array

### ISSUE THREAD

**Issue by gauthammuppalla** [mikolajmitura/java-properties-to-json#45] opened 2019-07-25 07:57 UTC
2D arrays are not being parsed properly

**Comment by gauthammuppalla** [comment] 2019-07-25 07:58
pl.jalokim.propertiestojson.util.exception.ParsePropertiesException: Current array element: 'coordinates[0]' is already considered as object JSON Element not as primitive because already this field has value:

This is the error I'm getting

**Comment by mikolajmitura** [comment] 2019-07-25 13:35
I suppose the problem is like below:
```properties
array[0][0]=test00
array[0][1]=test01
array[0][2]=test02
array[1][0]=test10
array[1][1]=test11
```

expected value:
```json
{  
   "array":[  
      [  
         "test00",
         "test01",
         "test02"
      ],
      [  
         "test10",
         "test11"
      ]
   ]
}
```

**Comment by gauthammuppalla** [comment] 2019-07-25 14:49
Yes, is this functionality available already?

**Comment by mikolajmitura** [comment] 2019-07-26 07:16
not yet... ;/

**Comment by gauthammuppalla** [comment] 2019-07-26 12:27
Could you attach a small ReadMe file about the current code framework which I could go through, to try and add this feature?

**Comment by mikolajmitura** [comment] 2019-07-29 06:48
I'm working on that at this moment. 
Now you can try with code from branch fature/multi_dim_array, but multi dimensional array should work.
But not all tests pass correctly now, you can skip them or ignore. 
If I resolve all problems then I will release new version. 
And thanks for you issue :-)

**Comment by mikolajmitura** [comment] 2019-08-05 18:48
this issue resolved in 5.0.0 version.
Should be available through in few hours at central maven repository.

**Closed** 2019-08-06 06:34 UTC
